# Generated by Django 3.0.8 on 2021-10-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211030_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_equip',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
